name: suggestions_plus
description: A simple command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  nyxx: ^6.7.0
  path: ^1.9.1
  vm_service: ^15.0.2
  # path: ^1.8.0
  hotreloader: ^4.3.0

dev_dependencies:
  lints: ^5.0.0
